<a href="https://colab.research.google.com/github/r0cd7b/DSAC/blob/master/lab_03_tensor_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensor Manipulation
- from Prof. Sunghun Kim's lecture lab
- modified by jyj

In [1]:
# https://www.tensorflow.org/api_guides/python/array_ops
import tensorflow as tf
import numpy as np
import pprint
np.random.seed(17)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)

## Simple Array

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

[0. 1. 2. 3. 4. 5. 6.]
1
(7,)
0.0 1.0 6.0
[2. 3. 4.] [4. 5.]
[0. 1.] [3. 4. 5. 6.]


# 2D Array

In [3]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
pp.pprint(t)
print(t.ndim) # rank
print(t.shape) # shape

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])
2
(4, 3)


## Shape, Rank, Axis

In [70]:
t = tf.constant([1,2,3,4])
t.numpy(), t.dtype, t.shape, tf.shape(t)

(array([1, 2, 3, 4], dtype=int32),
 tf.int32,
 TensorShape([4]),
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([4], dtype=int32)>)

In [5]:
t = tf.constant([[1,2],
                 [3,4]])
tf.shape(t)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [6]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [72]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
t

<tf.Tensor: shape=(1, 2, 3, 4), dtype=int32, numpy=
array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]]], dtype=int32)>

## Matmul VS multiply

In [8]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2)

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[12.]], dtype=float32)>

In [9]:
matrix1*matrix2    # broadcasting (be careful when using)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[6., 6.],
       [6., 6.]], dtype=float32)>

## Watch out broadcasting

In [10]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
matrix1+matrix2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[5., 5.],
       [5., 5.]], dtype=float32)>

In [11]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
matrix1+matrix2

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[5., 5.]], dtype=float32)>

## Random values for variable initializations 

In [12]:
tf.random.normal([3], mean=0., stddev=1.0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([ 0.55666524, -0.52381545,  1.2287319 ], dtype=float32)>

In [13]:
tf.random.uniform([2])  # For floats, the default range is [0, 1).  
                        # for ints, at least maxval must be specified explicitly.

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.57156205, 0.04330528], dtype=float32)>

In [14]:
tf.random.uniform([2, 3])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.3667941 , 0.7744527 , 0.5910549 ],
       [0.1047194 , 0.35488856, 0.28950012]], dtype=float32)>

## Reduce Mean/Sum

In [15]:
tf.reduce_mean([1., 2.], axis=0)

<tf.Tensor: shape=(), dtype=float32, numpy=1.5>

In [16]:
x = [[1., 2.],
     [3., 4.]]

tf.reduce_mean(x), tf.reduce_mean(x, axis=0)

(<tf.Tensor: shape=(), dtype=float32, numpy=2.5>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>)

In [17]:
tf.reduce_mean(x, axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 3.], dtype=float32)>

In [18]:
tf.reduce_mean(x, axis=1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>

In [19]:
tf.reduce_mean(x, axis=-1)  # 가장 안쪽 axis

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>

In [20]:
tf.reduce_sum(x)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [21]:
tf.reduce_sum(x, axis=0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4., 6.], dtype=float32)>

In [22]:
tf.reduce_sum(x, axis=-1)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 7.], dtype=float32)>

In [23]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1))

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

## Argmax with axis

In [24]:
x = [[0, 1, 2],
     [2, 1, 0]]
tf.argmax(x, axis=0)

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 0, 0])>

In [25]:
tf.argmax(x, axis=1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 0])>

In [26]:
tf.argmax(x, axis=-1)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([2, 0])>

## Reshape, squeeze, expand_dims

In [27]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [28]:
tf.reshape(t, shape=[-1, 3])

<tf.Tensor: shape=(4, 3), dtype=int64, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])>

In [29]:
tf.reshape(t, shape=[-1, 1, 3])

<tf.Tensor: shape=(4, 1, 3), dtype=int64, numpy=
array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])>

In [30]:
tf.squeeze([[0], [1], [2]])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 1, 2], dtype=int32)>

In [31]:
tf.expand_dims([0, 1, 2], 0), tf.expand_dims([0, 1, 2], 1)  # axis 추가

(<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[0, 1, 2]], dtype=int32)>,
 <tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2]], dtype=int32)>)

## One hot

In [32]:
tf.one_hot([[0], [1], [2], [0]], depth=3) # rank 가 하나 늘어남

<tf.Tensor: shape=(4, 1, 3), dtype=float32, numpy=
array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)>

In [33]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)>

## casting

In [34]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32)   # type 변경

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [35]:
print([True, False, 1 == 1, 0 == 1])
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32)  # True->1, False->0

[True, False, True, False]


<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 0, 1, 0], dtype=int32)>

## Stack

In [36]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z])

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [37]:
tf.stack([x, y, z], axis=1)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

## Ones like and Zeros like

In [38]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x)  # 모양이 같게

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1]], dtype=int32)>

In [39]:
tf.zeros_like(x)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

## Zip


In [40]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [41]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


## Transpose

In [42]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [43]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(t1.shape)
pp.pprint(t1)

TensorShape([2, 2, 3])
<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])>


In [44]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(t.shape)
pp.pprint(t)

TensorShape([2, 2, 3])
<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])>


In [45]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(t2.shape)
pp.pprint(t2)

TensorShape([2, 3, 2])
<tf.Tensor: shape=(2, 3, 2), dtype=int64, numpy=
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])>


In [46]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(t.shape)
pp.pprint(t)

TensorShape([2, 2, 3])
<tf.Tensor: shape=(2, 2, 3), dtype=int64, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])>


# Numpy and Tensorflow

In [47]:
import numpy as np
import tensorflow as tf

In [48]:
tf.__version__

'2.3.0'

In [49]:
print(tf.random.normal([5]).numpy())

print(np.random.randn(5))


[-0.14903891  1.1582223  -1.4975111   0.90941375  1.2075504 ]
[ 0.27626589 -1.85462808  0.62390111  1.14531129  1.03719047]


In [50]:
np.random.seed(17)
print(tf.random.normal([2,3]))
print(np.random.randn(2,3))

tf.Tensor(
[[ 0.09770985 -0.71870035 -0.07405096]
 [-0.15629645  0.16885436 -0.06524113]], shape=(2, 3), dtype=float32)
[[ 0.27626589 -1.85462808  0.62390111]
 [ 1.14531129  1.03719047  1.88663893]]


In [51]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
tf.ones([2,3]), tf.ones((2,3))

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>)

In [53]:
tf.ones((2)).numpy()

array([1., 1.], dtype=float32)

In [54]:
tf.ones((2,)).numpy(), tf.ones((1,2)).numpy()

(array([1., 1.], dtype=float32), array([[1., 1.]], dtype=float32))

In [55]:
tf.ones((1)).numpy(), np.ones(1)

(array([1.], dtype=float32), array([1.]))

In [56]:
tf.constant(3, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [57]:
np.array([1,2,3,4]).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [58]:
tf.constant([1,2,3,4], shape=[2,2])

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [59]:
tf.constant([1,2,3,4])

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>

In [60]:
x = tf.constant([1,2,3,4], shape=[2,2])
tf.zeros_like(x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [61]:
tf.fill([3,3], 6)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]], dtype=int32)>


## define and initializing variables


In [62]:
a0 = tf.Variable([1,2,3,4], dtype = tf.float32)
b = tf.constant(2, tf.float32)
a0*b

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([2., 4., 6., 8.], dtype=float32)>

In [63]:
tf.multiply(a0, b) == a0 * b

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True,  True,  True,  True])>

In [64]:
A2 = tf.constant([[1,2],[3,4]])
B2 = tf.constant([[5,6],[7,8]])
A2 + B2, A2 * B2, tf.add(A2, B2), tf.multiply(A2, B2)  # element-wise

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 6,  8],
        [10, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 5, 12],
        [21, 32]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 6,  8],
        [10, 12]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 5, 12],
        [21, 32]], dtype=int32)>)

In [65]:
tf.matmul(A2, B2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [66]:
tf.reduce_sum(A2), tf.reduce_sum(A2, axis=0), tf.reduce_sum(A2, axis=1)

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 7], dtype=int32)>)

## advanced functions

- gradient(), reshape(), random()


In [67]:
x = tf.Variable(-1.0)
with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.multiply(x, x)
    
g = tape.gradient(y, x)
g.numpy()

-2.0

In [68]:
gray1 = tf.random.uniform([2,2], maxval=255, dtype='int32')
gray2 = tf.reshape(gray1, [2*2, 1])
gray1, gray2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[202, 162],
        [105, 113]], dtype=int32)>,
 <tf.Tensor: shape=(4, 1), dtype=int32, numpy=
 array([[202],
        [162],
        [105],
        [113]], dtype=int32)>)

In [69]:
color = tf.random.uniform([2,2,3], maxval=255, dtype='int32') # color image
tf.reshape(color, [2*2, 3])

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[224, 215, 137],
       [111, 194,  47],
       [100,  87,  40],
       [152,  44,  17]], dtype=int32)>